version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 192.168.1.5:8443:443
    volumes:
      - ./ssl/:/etc/nginx/ssl
      - static_volume:/etc/nginx/static
    networks:
      - webnet

  django:
    build:
      context: ./transcendece
    command: bash -c "python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
    networks:
      - webnet

volumes:
  static_volume:

networks:
  webnet: