version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mypostgres
      POSTGRES_USER: mtoiasql
      POSTGRES_PASSWORD: "1235678"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db

volumes:
  postgres_data: