version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mypostgres
      POSTGRES_USER: mtoiasql
      POSTGRES_PASSWORD: "1235678"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
volumes:
  postgres_data: