# Generated by Django 4.2.11 on 2024-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomname',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
