# Generated by Django 5.0.4 on 2024-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_roomname_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomname',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
