# Generated by Django 5.0.4 on 2024-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_tournament_match_name_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournametPlaceHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerNumber', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
