# Generated by Django 5.0.4 on 2024-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_roomname_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomname',
            name='level',
            field=models.FloatField(default=0),
        ),
    ]
