# Generated by Django 5.0.4 on 2024-05-19 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_tournametplaceholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_match',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tournament_match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournament_match',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='tournament_match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournament_match',
            name='player2_score',
        ),
        migrations.RemoveField(
            model_name='tournament_match',
            name='result',
        ),
        migrations.AddField(
            model_name='roomname',
            name='tournament',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='room_name',
            field=models.CharField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='score_user1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='score_user2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament_match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Turnament_won_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
