# Generated by Django 5.0.4 on 2024-05-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_remove_tournament_match_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomname',
            old_name='public',
            new_name='friendly',
        ),
    ]
