# Generated by Django 5.0.4 on 2024-05-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_tournamentpartecipants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='match',
        ),
    ]
