# Generated by Django 5.0.4 on 2024-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_remove_tournament_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(to='pong.tournament_match'),
        ),
    ]
