# Generated by Django 5.0.4 on 2024-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_tournament_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournametplaceholder',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
