# Generated by Django 5.0.4 on 2024-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0014_tournametplaceholder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournametplaceholder',
            name='name',
            field=models.CharField(default='None', max_length=255, unique=True),
        ),
    ]
