# Generated by Django 5.0.4 on 2024-06-21 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0016_rename_tournametplaceholder_tournamentplaceholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTournament_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='None', max_length=254)),
                ('user1', models.CharField(default='None', max_length=254)),
                ('user2', models.CharField(default='None', max_length=254)),
                ('score_user1', models.PositiveIntegerField(default=0)),
                ('score_user2', models.PositiveIntegerField(default=0)),
                ('winner', models.CharField(default='None', max_length=254)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(default='None', max_length=254)),
                ('matches', models.ManyToManyField(to='pong.localtournament_match')),
            ],
        ),
    ]
