# Generated by Django 4.2.11 on 2024-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pro_pic',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg'),
        ),
    ]
