# Generated by Django 5.0.4 on 2024-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Ai',
            field=models.BooleanField(default=False),
        ),
    ]
