# Generated by Django 5.0.4 on 2024-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_status_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_login',
            field=models.BooleanField(default=False),
        ),
    ]
