# Generated by Django 5.0.4 on 2024-06-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_paddle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='OAuth',
            field=models.BooleanField(default=False),
        ),
    ]
