# Generated by Django 4.2.11 on 2024-03-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_friend_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
