# Generated by Django 4.2.11 on 2024-04-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='room_name',
            field=models.CharField(default='None', max_length=254),
        ),
    ]
