# Generated by Django 5.0.4 on 2024-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_paddle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paddle_color',
            field=models.CharField(default='#00FF99', max_length=254),
        ),
    ]
