# Generated by Django 5.0.4 on 2024-06-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_name_chat_roomname_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
