# Generated by Django 5.0.4 on 2024-05-13 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_roomlocal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlocal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
