# Generated by Django 5.0.4 on 2024-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paddle_color',
            field=models.CharField(default='white', max_length=254),
        ),
    ]
