# Generated by Django 5.0.4 on 2024-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pong_color',
            field=models.CharField(default='white', max_length=254),
        ),
    ]
