# Generated by Django 5.0.4 on 2024-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_pong_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pong_color',
            field=models.CharField(default='#141414', max_length=254),
        ),
    ]
