# Generated by Django 5.0.4 on 2024-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_pong_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paddle_color',
            field=models.CharField(default='#CC0505', max_length=254),
        ),
    ]
