# Generated by Django 5.0.4 on 2024-06-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_paddle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alias',
            field=models.CharField(default='None', max_length=254),
        ),
    ]
