# Generated by Django 5.0.4 on 2024-04-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomname',
            old_name='user',
            new_name='opponent',
        ),
    ]
