# Generated by Django 5.0.4 on 2024-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_tournamentroomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
