# Generated by Django 5.0.4 on 2024-06-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0015_alter_tournametplaceholder_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournametPlaceHolder',
            new_name='TournamentPlaceHolder',
        ),
    ]
