# Generated by Django 4.2.11 on 2024-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_login',
            field=models.CharField(default='Offline', max_length=50),
        ),
    ]
