# Generated by Django 4.2.11 on 2024-03-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_friends_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='friends',
            new_name='friends_list',
        ),
    ]
